name: Domain settings
type: module
description: Provides editable settings per domain
core_version_requirement: ^10
package: Custom

dependencies:
  - webform:webform
  - domain_settings:domain_settings
